version: '3.8'

services:
  backend:
    build: .
    container_name: privadas_backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: https://privdelparque-backend-oqissi-9aca91-31-97-41-99.traefik.me
    restart: always

  db:
    image: postgres:16
    container_name: privadas_db
    restart: always
    environment:
      POSTGRES_DB: privadas_del_parque
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
