version: '3.8'

services:
  backend:
    build: .
    container_name: privadas_backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: privadas_db
    restart: always
    environment:
      POSTGRES_DB: privadas_del_parque
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
